### ISSUE TITLE
Build failure in Visual Studio 2015.

### ISSUE THREAD

**Issue by yasharvc** [codehollow/FeedReader#13]
I got following error:

> error MSB4041: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.

**Comment by codehollow** [comment]
sorry, VS2015 is not supported - please use the nuget package or update to VS2017
