### ISSUE TITLE
HTTPStatusCode 301 - Moved Support

### ISSUE THREAD

**Issue by moflaherty** [codehollow/FeedReader#15]
Hi! Possible suggestion for supporting both 301 and 308 status codes? Reference: [https://stackoverflow.com/questions/42136829/whats-difference-between-http-301-and-308-status-codes](url)

Helpers.DownloadAsync lines 54 (new) and 55 (changed):

`var statusCode = (int)response.StatusCode;
if (autoRedirect && (statusCode == 301 || statusCode == 308)) // moved` 

Example returning a 301 status code: [http://www.medicalnewstoday.com/rss/diabetes.xml](url)

**Comment by codehollow** [comment]
Hi! 
I fixed an encoding issue today and with this issue, I also added support for 301 status code: see:
https://github.com/codehollow/FeedReader/commit/bd782485204bc8b69f8a27be4985278b8eb9f32c
