### ISSUE TITLE
Async Issue

### ISSUE THREAD

**Issue by Chorger** [codehollow/FeedReader#17]
Hello!
When trying to use your FeedReader in UWP-type application the app deadlocks.
I made all necessary changes to the code so it works, but I don't know how to commit here. 
I'll leave a link to OneDrive, where the folder with the project is.
[https://1drv.ms/f/s!AtuQdKOJRdhQgegqnpHHrZgnwRQZfw](url)
Best wishes, 
Tim

**Comment by codehollow** [comment]
Hallo!
fixed with last merge - thanks to @inyutin-maxim 
best regards,
Armin
