### ISSUE TITLE
.Net Core 2.1 Support and More Deadlocks

### ISSUE THREAD

**Issue by curtiswellborn** [codehollow/FeedReader#18]
- I want to add .netcore 2.1 support
- I want to bump .netstandard from 1.3 to 2.0
- I want to fix a couple more potential deadlocks
- I want to make a ReadFromFileAsync

**Comment by curtiswellborn** [comment]
Not sure how to assign this to myself but putting in a pr that covers all of these.

**Comment by codehollow** [comment]
fixed by @curtiswellborn, nuget package updated today
