### ISSUE TITLE
HTTP 302 handling

### ISSUE THREAD

**Issue by torresdavida** [codehollow/FeedReader#23]
I have a number of RSS feeds responding with an HTTP 302 requiring a redirect, which I was able to resolve by cloning the repo and altered this line of code in FeedReader/Helpers.cs - line 59.

```
if (autoRedirect && (statusCode == 301 || statusCode == 302|| statusCode == 308)) 
```

Should I submit a pull request for this change?

**Comment by codehollow** [comment]
fixed in the latest version (1.2.0)
