### ISSUE TITLE
HtmlAgilityPack Dependency

### ISSUE THREAD

**Issue by voidmonk** [codehollow/FeedReader#25]
Hi, it looks like the library uses native `XDocument` (`System.Xml.Linq`) for parsing the feeds, but also has a dependency on HtmlAgilityPack to fetch & parse HTML I suppose.

Is there a way to remove or separate the dependency on HtmlAgilityPack, as we don't use it nor need it as part of our project like many other users? We can just inject feed data using `FeedReader.ReadFromString`.

I guess we can run `Install-Package CodeHollow.FeedReader -IgnoreDependencies` to install the nuget package without dependencies, but I'm not sure if it will compile and if package restore at build time will work the same.

**Comment by codehollow** [comment]
removed in the latest version 1.2.0

**Comment by voidmonk** [comment]
Thank you. This is great for simplified codebase, and a lighter package.
