### ISSUE TITLE
How to find item thumbnail of Youtube Feed?

### ISSUE THREAD

**Issue by tuanbs** [codehollow/FeedReader#32]
Hi @codehollow,

Could you tell me how to get the item thumbnail of Youtube Feed?
For example, if I read the `Ted Talk` from url feed `https://pa.tedcdn.com/feeds/talks.rss`, then I can get the thumbnail of each item using the following codes:
```cs
string feedUrl = "https://pa.tedcdn.com/feeds/talks.rss"; // This works.
// string feedUrl = "https://www.youtube.com/feeds/videos.xml?channel_id=UCAuUUnT6oDeKwE6v1NGQxug"; // This won't work.
var feed = await FeedReader.ReadAsync(feedUrl);
var xDocument = XDocument.Parse(feed.OriginalDocument);
var xNamespace = xDocument.Root.GetDefaultNamespace();

foreach(var item in feed.Items)
{
    var baseFeedItem = item.SpecificItem;
    string thumbnail = null;
    if (baseFeedItem.Element.Descendants().Any(x => x.Name.LocalName == xNamespace + "thumbnail"))
    {
        thumbnail = baseFeedItem.Element.Descendants().First(x => x.Name.LocalName == xNamespace + "thumbnail").Attribute("url").Value;
    }
    Console.WriteLine("thumbnail is: " + thumbnail);
}
```

But if I read `Ted Talk` feed from its Youtube channel `https://www.youtube.com/feeds/videos.xml?channel_id=UCAuUUnT6oDeKwE6v1NGQxug`, then I cannot get the thumbnail.

**Comment by MustafaBKLZ** [comment]
Hello tuanbs,
I'm sorry for you don't get answer from publisher. But your had send codes well work for me. I've been trying for almost an hour get thumbnail.

**Comment by codehollow** [comment]
Hello tuanbs,

one way to fix this is to use:
`                if (baseFeedItem.Element.Descendants().Any(x => x.Name.LocalName.Contains("thumbnail", StringComparison.InvariantCultureIgnoreCase)))
                {
                    thumbnail = baseFeedItem.Element.Descendants().First(x => x.Name.LocalName.Contains("thumbnail", StringComparison.InvariantCultureIgnoreCase)).Attribute("url").Value;
                }
`
